### ISSUE TITLE
Is there a cfndsl discussion forum

### ISSUE THREAD

**Issue by yumpy** [stevenjack/cfndsl#111]
Is there a cfndsl discussion forum? I'd prefer to raise questions and ideas outside of the issue tracker. Thus leaving the issue tracker for tracking issues

eg https://github.com/atom/atom uses http://www.discourse.org/
see: https://discuss.atom.io/

**Comment by stevenjack** [comment]
@yumpy There's a gitter channel a the top of the readme: https://gitter.im/stevenjack/cfndsl?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by yumpy** [comment]
Thanks. I'd missed that.
