### ISSUE TITLE
Build stacks by including other ruby files

### ISSUE THREAD

**Issue by johnf** [stevenjack/cfndsl#152]
I've created a naive implementation in #151 which would allow the following

 
You have a master file ```env_stack.rb```
``` ruby
CloudFormation {
  Description "Test"
  include 'parameters_one'
  include 'parameters_two'
}
```

you can then create ```_parameters_one.rb``` and ```_parameters_two.rb```
``` ruby
Parameter("One") {
  String
}
```

``` ruby
Parameter("Two") {
  String
}
```

This will generate the same output as
``` ruby
CloudFormation {
  Description "Test"
  Parameter("One") {
    String
  }
  Parameter("Two") {
    String
  }
}
```

Does this make sense?

**Comment by stevenjack** [comment]
@johnf really like this idea, interesting how you're able to define a method called `include` - I thought it was a reserved keyword.

I'll take a look at the PR, I'd done something similar in a previous project but by including the different templates into one big eval, this makes a lot more sense. Nice work!

**Comment by johnf** [comment]
```include``` probably is technically reserved but probably only inside a module so that might be why it works here. Actually according to http://docs.ruby-lang.org/en/2.2.0/keywords_rdoc.html maybe it isn't reserved?

I was going to go with ```Include``` originally but didn't want to risk AWS using it for something.

Maybe ```_Include``` ?

**Comment by stevenjack** [comment]
I'll continue the conversation in: https://github.com/stevenjack/cfndsl/pull/151

**Comment by johnf** [comment]
Closing based on discussion in #151
