### ISSUE TITLE
Cannot exclude Metadata With if defined

### ISSUE THREAD

**Issue by geoffreyharrison** [stevenjack/cfndsl#159]
We're currently working on a Project where we are trying to define Metadata for Auto Scaling Groups. We're currently having an issue where if we code in something like:

`Metadata('AWS::CloudFormation::Init',metadata) if defined?(metadata)`

The resulting cloudformation will try to render regardless of whether the metadata variable is defined or not. The error when there is no metadata data defined is:

```
cfndsl/module.rb:60:in `block (4 levels) in dsl_content_object': wrong number of arguments (0 for 1+) (ArgumentError)
	from /home/vagrant/Projects/Bulletproof/Movember/cfndsl/AutoScalingGroups.rb:240:in `block (2 levels) in eval_file_with_extras'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl/CloudFormationTemplate.rb:157:in `instance_eval'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl/CloudFormationTemplate.rb:157:in `block (4 levels) in <class:CloudFormationTemplate>'
	from /home/vagrant/Projects/Bulletproof/Movember/cfndsl/AutoScalingGroups.rb:233:in `block in eval_file_with_extras'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl/JSONable.rb:176:in `instance_eval'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl/JSONable.rb:176:in `declare'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl.rb:90:in `CloudFormation'
	from /home/vagrant/Projects/Bulletproof/Movember/cfndsl/AutoScalingGroups.rb:17:in `eval_file_with_extras'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl.rb:83:in `eval'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/lib/cfndsl.rb:83:in `eval_file_with_extras'
	from /var/lib/gems/2.2.0/gems/cfndsl-0.4.0/bin/cfndsl:61:in `<top (required)>'
	from /usr/local/bin/cfndsl:23:in `load'
	from /usr/local/bin/cfndsl:23:in `<main>'
```

Just want to know if there is a way to fix this. Currently, we are defining metadata as an empty string if it doesn't exist but it would be better for the Metadata tag to simply not exist in the resulting output.

Thanks.

**Comment by stevenjack** [comment]
@geoffreyharrison The problem here is that the DSL is being parsed so no matter what the condition is your have around the DSL method, it'll still be passed and we attempt to convert it into a definition class. For the moment the best way is to default it to an empty string, I'll put an issue in to see if there's a way of indicating that we only want to include a resource property if say a condition is satisfied or maybe if the argument to the method actually exists.
