### ISSUE TITLE
Code Cleanup?

### ISSUE THREAD

**Issue by johnf** [stevenjack/cfndsl#160]
Howdy,

I'd like to make some more contributions to cfndsl but every time I start I find I'm held up a bit by the code. Lots of extra whitespace and some inconsistencies.

Any thoughts on using something like rubocop and doing a cleanup?

I'm happy to do the work but don't want to start if others don't feel it's worth it.

**Comment by stevenjack** [comment]
@johnf I've had the same feeling, just been trying to find some time to work on it recently. I've got a few weeks off next week and this was one of the improvements I wanted to focus on so will have a PR for it shortly.

**Comment by johnf** [comment]
@stevenjack I had some time last night so I made a start on it https://github.com/johnf/cfndsl/tree/rubocop

Created a rubocop.yml which I think is close as possible to what current code styles where.

Currently it is rubocop clean but I put a bunch of stuff in the rubocop.yml with ```FIXME``` that I still want to explore and try to improve one.

Unless you want to go in a direction I'm happy to keep picking away at it.

Key feedback I'm after is anything specific you want in rubocop.yml? e.g. hash rockets vs 1.9 syntax is usually they key holy war :)

**Comment by stevenjack** [comment]
@johnf Great work so far thanks for starting this, in terms of hash rockets vs 1.9 syntax I'd like the bring this up to date and have the new syntax as the expected version.

I'd like to help out and I think the best way to move forward is I'll create a branch from your changes on here and start working on it from the top down and you could work from the bottom up? Obviously going to be some issues with conflicts but we should be able to resolve them. Branch will be called: `johnf_rubocop`.

**Comment by johnf** [comment]
@stevenjack sounds like a plan. Looks like we're working in almost opposite time zones so I think if we merge from each other before we start any work it shouldn't be too painful.

**Comment by johnf** [comment]
@stevenjack Can you check https://github.com/johnf/cfndsl/commit/28450618d209500666dc2f7d387fc1451613567b
I added some TODOs. Not sure if what's happening in there is a bug or not since we iterate through the array but do anything with the contents
