### ISSUE TITLE
External Parameters

### ISSUE THREAD

**Issue by kornypoet** [stevenjack/cfndsl#170]
### Problems
The current configuration system could use some attention. These are the arguments for changing its behavior:

* Using `binding.eval` to set constants is an unsafe Ruby practice.
* Because the above method was chosen, there are potential variable, method or constant name collisions possible (you could name your configuration keys too similar to library methods or existing constants).
* There is no way to address the configuration as a whole, perhaps to implement environments, or turn all configuration keys into `Parameter` defaults.
* The `-D` option is a powerful override for a specific key-value pair from the invocation, but right now it's interpreted as raw Ruby, and this should be guarded against.

### Proposal

Implement an `ExternalParameters` configuration class. Move all of the logic of reading configuration files into this class, and remove the `binding` implementation. An instance of this class would be created for every time `CloudFormation` is invoked, and assigned to an easily recognizable method name. `ExternalParameters` would have all of the normal associated behavior of a regular Ruby hash. `-D` options on the command line turn into key-value entries in the configuration hash. Lastly, keep the old behavior around for a few releases with the option to disable/deprecate. In this case, the class would also assign the constants in the old way, to not break existing implementations.

### Benefits

* Clarified and standardized approach to configuration. All configuration behavior and logic is clean, and implemented in one dedicated class.
* Access configuration as an entity, or separately as keys and values. Powerful and flexible.
* Since the behavior is encapsulated, end users can extend the behavior to implement additional functionality, namely environments.
* Configuration behaves as a `Hash`, with all of the benefits and expectations associated.
* A single class is more easily testable.

### Example

Some examples of how this would work (for discussion points, not a final implementation):

#### Keep existing behavior

Given a yaml file `config.yaml`:

```yaml
---
FOO: foo
BAR: bar
```

Invoking `cfndsl template.rb -y config.yaml`

```ruby
# template.rb
# Both behaviors
CloudFormation do
  ExternalParameters[:FOO] #=> 'foo'
  FOO #=> 'foo'
end
```

#### More flexible access

Given a yaml file `config.yaml`:

```yaml
---
# Allow users to use lowercase config entries, something previously difficult to do
foo: foo
bar: bar
```

Invoking `cfndsl template.rb -y config.yaml`

```ruby
# template.rb
CloudFormation do
  ExternalParameters[:foo] #=> 'foo'
  # We could easily implement indifferent access if desired
  ExternalParameters['foo'] #=> 'foo'
  # You can also address all configuration at the same time
  ExternalParameters.each_pair do |key, val|
    # ...
  end
end
```

#### Implementing environments

Given a yaml file `config.yaml`:

```yaml
---
production:
   ...
development:
  ...
```

Invoking `cfndsl template.rb -y config.yaml -D environment=production`

```ruby
# template.rb
CloudFormation do
  environment = ExternalParameters[:environment]
  config = ExternalParameters.fetch environment
  # use only production config
  # ...
end
```

**Comment by gergnz** [comment]
@kornypoet this looks awesome. Can we go even further?  if -y is a directory, load all the yaml directly in that directory and use say -r, to load yaml recursively from that direct down. Thoughts?

**Comment by kornypoet** [comment]
I think we should leave the behavior of `-y` intact to not break current implementations.
Loading all in a directory and/or loading recursively is certainly doable, but needs to come with clear explanations of load order and behavior. It's simple enough to piggyback it here, but perhaps it should be made a separate request following this one?

**Comment by stevenjack** [comment]
@kornypoet I was thinking the same when I was writing the example in https://github.com/stevenjack/cfndsl/issues/167 that the way we just globally define configuration constants was a fairly kludgy. 

This proposal makes a lot of sense and agree we should probably look at the recursive load in a separate PR once this one's merged.

@kornypoet Are you looking to work on this? I can start looking at it this eve if not as I've got some available time.

**Comment by kornypoet** [comment]
@stevenjack I've got code ready to go. I'll have a PR out later today :smile:

**Comment by stevenjack** [comment]
This guys on :fire:, nice one!

**Comment by kornypoet** [comment]
stevenjack/cfndsl#172

**Comment by stevenjack** [comment]
Resolved by https://github.com/stevenjack/cfndsl/pull/179

**Comment by eric-tucker** [comment]
Isn't displaying this warning message to users about deprecation confusing when they're not even using the deprecated feature?

"The creation of constants as config is deprecated!"

I'm not even creating constants as config.  At least I don't think I am.  Get my point?  Why was the decision made to just always spit out this message?  I'm confused.

**Comment by gergnz** [comment]
I tend to agree @eric-tucker. It's now become a habit to just add _-b_ to all new builds and anything that gets fixed up.

**Comment by zsustar** [comment]
I am totally new to cfndsl.

I'm using JSON to edit CF for a quite long time and today one of my friend told me cfndsl is a good to go. So, I just did a sample run today from "README.md ", however it always showing "The creation of constants as config is deprecated!" no matter what code I put in the ruby file.

Could anyone please share some information about how to run my "Hello World" ? Thanks!
OS version: RedHat 7.x on AWS
Ruby version: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
cfndsl version: 0.14.0

Error output as following:

`[ec2-user@ruby]$ **cfndsl template.rb -y config.yaml**


  
The creation of constants as config is deprecated!
Please switch to the #external_parameters method within your templates to access variables
See https://github.com/stevenjack/cfndsl/issues/170
Use the --disable-binding flag to suppress this message
/usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/types.rb:16:in `included': undefined method `safe_load' for Psych:Module (NoMethodError)
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/os/types.rb:9:in `include'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/os/types.rb:9:in `<module:Types>'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/os/types.rb:6:in `<module:OS>'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/os/types.rb:4:in `<module:CfnDsl>'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/os/types.rb:3:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/orchestration_template.rb:4:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl/aws/cloud_formation_template.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/lib/cfndsl.rb:19:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/cfndsl-0.14.0/bin/cfndsl:123:in `<top (required)>'
        from /usr/local/bin/cfndsl:23:in `load'
        from /usr/local/bin/cfndsl:23:in `<main>'
`

**Comment by gergnz** [comment]
Hi @zsustar,

Your issue is not the same as this thread. It looks like safe_load was introduced in ruby 2.1.0.

I'll raise an issue to make sure it's noted.  I'd suggest you take a look at https://rvm.io/ or https://github.com/rbenv/rbenv to use cfndsl on EL7 and derivatives.
