### ISSUE TITLE
Improper JSON output for dimensions.

### ISSUE THREAD

**Issue by autotune** [stevenjack/cfndsl#174]
CloudFormation looks for the following json format per [the docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-dimension.html):

    "Dimensions": [
         {
            "Name": "AutoScalingGroupName",
            "Value": { "Ref": "WebServerGroup" }
         }
      ]

When a resource like the following is used:

    Resource("CloudWatchCPU") do
       Type("AWS::CloudWatch::Alarm")
       Property("AlarmDescription", "CloudWatchCPU")
       Property("MetricName", "CloudWatchCPU")
       Property("Namespace", "AWS/EC2")
       Property("Statistic", "Average")
       Property("Period", "300")
       Property("EvaluationPeriods", "1")
       Property("Threshold", "95")
       Property("Dimensions", ["Name: CPUUtilization", "Value: i-12345678"])

We get the following result:

        "Dimensions": [
          "Name: CPUUtilization",
          "Value: i-12345678"
        ],

which results in the template failing. Using the following syntax works:

        "Dimensions": [
          {
          "Name": "CPUUtilization",
          "Value": "i-12345678"
          }
        ],

Happy to take a crack at this here, just documenting the issue before doing so.

**Comment by stevenjack** [comment]
Hey @autotune I had a quick look myself and here's what I'm finding, so we're looking to generate:

```json
"Dimensions": [
     {
        "Name": "AutoScalingGroupName",
        "Value": { "Ref": "WebServerGroup" }
     }
  ]
```
and in your first example you're adding them like:

```ruby
Property("Dimensions", ["Name: CPUUtilization", "Value: i-12345678"])
```

Which I would expect to return an array of two items not an array with a hash with two keys `Name` and `Value`.

With the following template:

```ruby
CloudFormation do
  Description "Test stack"

  Resource("CloudWatchCPU") do
    Type("AWS::CloudWatch::Alarm")
    Property("AlarmDescription", "CloudWatchCPU")
    Property("MetricName", "CloudWatchCPU")
    Property("Namespace", "AWS/EC2")
    Property("Statistic", "Average")
    Property("Period", "300")
    Property("EvaluationPeriods", "1")
    Property("Threshold", "95")
    Property("Dimensions", [
      {
        "Name"  => "CPUUtilization",
        "Value" => "i-12345678"
      }
    ])
  end
end
```

i get the expected result:

```json
{
   "Description" : "Hey",
   "AWSTemplateFormatVersion" : "2010-09-09",
   "Resources" : {
      "CloudWatchCPU" : {
         "Properties" : {
            "EvaluationPeriods" : "1",
            "Dimensions" : [
               {
                  "Name" : "CPUUtilization",
                  "Value" : "i-12345678"
               }
            ],
            "Statistic" : "Average",
            "MetricName" : "CloudWatchCPU",
            "Period" : "300",
            "AlarmDescription" : "CloudWatchCPU",
            "Namespace" : "AWS/EC2",
            "Threshold" : "95"
         },
         "Type" : "AWS::CloudWatch::Alarm"
      }
   }
}
```

With the `Dimensions` node in the format you mentioned from the CF docs:

```json
"Dimensions" : [
  {
    "Name" : "CPUUtilization",
    "Value" : "i-12345678"
  }
]
```

I might just have completely missed the problem here but it seems to be generating what I expect for the dimensions?

**Comment by autotune** [comment]
Ah that did the trick, thanks @stevenjack.

**Comment by stevenjack** [comment]
@autotune no problem!
