### ISSUE TITLE
5.0 release breaks addTag 

### ISSUE THREAD

**Issue by jsywulak** [stevenjack/cfndsl#175]
I think the deprecation warning for addTag is broken. I'm getting this error:

```/var/lib/jenkins/.rvm/gems/ruby-2.2.1@gemset/gems/cfndsl-0.5.0/lib/cfndsl/resources.rb:15:in `addTag': private method `puts' called for #<Array:0x000000018501c8> (NoMethodError)```

Points to [this line](https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/resources.rb#L15). Sounds like logstream is an array during my run, not a logger? 

Not sure if this is something specific to my env or a bug. Let me know if you need more info!

**Comment by stevenjack** [comment]
@jsywulak Thanks for reporting this, I assume somewhere in your application you have something defined as `logstream` that's an array - Looking at the code here I'm not sure how it would ever have worked so I'm going to put a quick PR in to fix and and push a new release out.

**Comment by jsywulak** [comment]
No worries. It wasn't a huge deal: I just quickly searched and replaced to replace all our `addTag`s with `add_tag`s and we're chugging along fine now. :)

Thanks!!

**Comment by gergnz** [comment]
I'm seeing this too.  Going to fix up the tags.
