### ISSUE TITLE
Provide support for AWS::CloudFormation::CustomResource

### ISSUE THREAD

**Issue by howech** [stevenjack/cfndsl#18]
It would be nice if there were a way to include a way to declare the custom properties and attributes that the custom resource allows, as well.

**Comment by gergnz** [comment]
Just bumped into this one.  It's not obvious, but I'm going to take a look and see what I can work out.

**Comment by gergnz** [comment]
I was able to create arbitrary values using the Property method:
```ruby
  CloudFormation_CustomResource('TagElasticCache') do
    ServiceToken "arn:aws:lambda:ap-southeast-2:123456789012:function:myfunction"
    Property("Tags", [{'Key' => 'Name', 'Value' => 'myname'}])
    Property("Arn", "arn:aws:elasticache:ap-southeast-2:123456789012:resourcetype:resourcename")
  end
```
