### ISSUE TITLE
addTag breaks propogate argument

### ISSUE THREAD

**Issue by herebebogans** [stevenjack/cfndsl#184]
Hi all,

It seems the addTag function can now never set 

PropogateAtLaunch: true

Which is needed by any template that uses Autoscaling::Launchconfiguration.

I've submitted a pull request but not sure if this is the best fix.

**Comment by kornypoet** [comment]
Nice catch. You mentioned submitting a PR, but I don't see it, either open or closed?
In the meantime, you should use the `#add_tag` method, which is how it will be spelled going forward, and it _does_ correctly set `PropogateAtLaunch`.

**Comment by kornypoet** [comment]
Here's mine anyway: stevenjack/cfndsl#188

**Comment by herebebogans** [comment]
Sorry  - thought I submitted a PR but didn't finish it .. we've changed all our code to use add_tag but thanks for the fix.
