### ISSUE TITLE
Every Resource is of Type AWS::ApiGateway::Resource in version 0.9.1

### ISSUE THREAD

**Issue by ericzumba** [stevenjack/cfndsl#206]
Hey, Steven, 

This is a great tool! Thanks. 

I think a bug was introduced in version 0.9.1. When I run`cfndsl sample/autoscale.rb` all resources come out as `"Type": "AWS::ApiGateway::Resource"`. I maybe missing something, but I'm quite sure this is unexpected. Tested it out with version 0.9.0 and this behaviour does not exist.

I could not get my head around the problem, otherwise I'd gladly make a PR.

Hope this report helps. 

Thanks.

**Comment by stevenjack** [comment]
hey @ericzumba thanks for spotting this, am looking into it now - pretty sure it's to do with the layout of the `types.yml` so should be a fairly easy fix.

**Comment by ericzumba** [comment]
Cool, @stevenjack. Thanks for taking the time to look into this.
Nice work with the project btw. Excellent code.

**Comment by gergnz** [comment]
This one just popped up at work. I think you need to pull 0.9.1.

**Comment by gergnz** [comment]
Having a look at this one, it appears to literally be an issue with "Resource", in the type "AWS::ApiGateway::Resource". Digging further.

**Comment by ericzumba** [comment]
Wow, @gergnz. Nasty bug :D
