### ISSUE TITLE
0.11.0 removal of metadata has caused regression in existing templates

### ISSUE THREAD

**Issue by adcreare** [stevenjack/cfndsl#227]
#### Issue Description

Version 0.11.0 (commit https://github.com/stevenjack/cfndsl/commit/430b6a55f0c48f63de2b5e41856a8403e12054f9 ) has caused a breaking change to processing of MetaData elements in templates. 

The following snip from a ASG config will generate an error of: cfndsl/module.rb:25:in `block (4 levels) in dsl_attr_setter': wrong number of arguments (2 for 1) (ArgumentError)

```  
AutoScaling_LaunchConfiguration("LaunchConfig") {
    AssociatePublicIpAddress false
    Metadata('AWS::CloudFormation::Authentication', {
      "s3access" => {
          :type => "s3",
          :buckets => [Ref("ArtifactBucket")],
          :roleName => Ref("InstanceRole")
      }
    }) 
```

I believe this was a purposeful change under https://github.com/stevenjack/cfndsl/pull/209.

I would strongly suggest this isn't a good idea, I would expect this to cause a lot of issues for people using metadata configuration on ASG and the like both with existing and new templates.

From the aws documentation I don't see any specification for the use of MetaData in ASGs to perform tasks such as cloud formation authentication being deprecated ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-authentication.html

#### Temp Issue Workaround (for those googling)

Install the previous version using the following
gem uninstall cfndsl
gem install cfndsl -v 0.10.2

**Comment by gergnz** [comment]
Hi @adcreare,

Thanks for reporting this.

I think you just need to change the way you are specifying your Metadata.  For example:
```ruby
require 'cfndsl'

CloudFormation do
  Parameter('ArtifactBucket') do
    Type('String')
    Default 'foo'
  end
  Parameter('InstanceRole') do
    Type('String')
    Default 'foo'
  end

  AutoScaling_LaunchConfiguration("LaunchConfig") {
      AssociatePublicIpAddress false
      Metadata('AWS::CloudFormation::Authentication' => {
        "s3access" => {
            :type => "s3",
            :buckets => [Ref("ArtifactBucket")],
            :roleName => Ref("InstanceRole")
        }
      }) 
  }

end
```

produces
```js
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "ArtifactBucket": {
      "Type": "String",
      "Default": "foo"
    },
    "InstanceRole": {
      "Type": "String",
      "Default": "foo"
    }
  },
  "Resources": {
    "LaunchConfig": {
      "Properties": {
        "AssociatePublicIpAddress": false
      },
      "Metadata": {
        "AWS::CloudFormation::Authentication": {
          "s3access": {
            "type": "s3",
            "buckets": [
              {
                "Ref": "ArtifactBucket"
              }
            ],
            "roleName": {
              "Ref": "InstanceRole"
            }
          }
        }
      },
      "Type": "AWS::AutoScaling::LaunchConfiguration"
    }
  }
}
```

Note, I remvoed the "," and replaced it with a rocket "=>".

From the readme (yes I had to go and read @kornypoet's updated docs to understand it myself):
https://github.com/stevenjack/cfndsl#resource-metadata
_Arguments provided must be able to be JSON-ified_

Hope that helps.

**Comment by kornypoet** [comment]
Apologies for the breaking change to your template. We discussed this internally, and felt that the `MetaData` attribute was little-used enough that we could roll out the change with no impact. I'm sorry about that. The idea was to align `MetaData` more closely with the AWS [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html) than its current implementation. Previously, the method accepted two arguments and would automatically convert the result into a hash. Now it accepts a single argument, of any type, as long as it can be JSON-ified.
