### ISSUE TITLE
undefined method `LoadBalancer'

### ISSUE THREAD

**Issue by bksaurabh96** [stevenjack/cfndsl#229]
While setting up ELB I am getting no method error. Please have a look. Below are my code.

LoadBalancer(:ElasticLoadBalancer) do
	Type "AWS::ElasticLoadBalancing::LoadBalancer"
  end

**Error:**

 undefined method `LoadBalancer' for #<CfnDsl::CloudFormationTemplate:0x0000000240b008> (NoMethodError)
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/lib/cfndsl/jsonable.rb:173:in `instance_eval'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/lib/cfndsl/jsonable.rb:173:in `declare'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/lib/cfndsl.rb:94:in `CloudFormation'
        from /vagrant/test_cfndsl/wb.rb:3:in `eval_file_with_extras'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/lib/cfndsl.rb:88:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/lib/cfndsl.rb:88:in `eval_file_with_extras'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/cfndsl-0.11.0/bin/cfndsl:75:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/cfndsl:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/cfndsl:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp line 44.

**Comment by gergnz** [comment]
Hi @bksaurabh96,

LoadBalancer by itself isn't a valid type. You need to use _ElasticLoadBalancing_LoadBalancer_.

Also, if you use the name of the resource as the method, you don't need to specify type.

In your example the code should look like:
```ruby
ElasticLoadBalancing_LoadBalancer(:ElasticLoadBalancer) do
end
```
Hope that helps.

**Comment by bksaurabh96** [comment]
Thanks for your reply. Its working now.

**Comment by zetetic** [comment]
Just ran into this as well. Is there some heuristic/rule whereby we can infer the methods for each corresponding type? Or in other words, should this have been obvious to me?

**Comment by gergnz** [comment]
@zetetic in my mind (and that's just me), I look at the AWS Cloudfromation docs, remove the AWS:: and replace the second :: with _.

e.g.
```js
  "Resources": {
    "Foo": {
      "Type": "AWS::EC2::Instance"
```
becomes

```ruby
EC2_Instance(:Foo)
```
