### ISSUE TITLE
DSL to JSON mapping not working

### ISSUE THREAD

**Issue by bksaurabh96** [stevenjack/cfndsl#230]
I am doing a CFT conversion and figure out the issue while converting the JSOn into DSL format.
Below are the JSOn which I need but my DSL code is failing. I read examples but they are not helpful enough. Can anyone help here?

**Desired Output:**

"Mappings" : {
      "AWSInstanceType2Arch" : {
         "t2.nano" : {
            "Arch" : "HVM64"
         },
         "t1.micro" : {
            "Arch" : "PV64"
         },
       "AWSInstanceType2NATArch" : {
         "t1.micro1" : {
            "Arch" : "NATPV64"
         }
      }
   }
}

**My Code:**
Mapping(:AWSInstanceType2Arch, 
	't1.micro': { Arch: "PV64" }, 
	"t2.nano": { "Arch": "HVM64" },
	{ AWSInstanceType2NATArch, 
	"t1.micro1": { "Arch": "NATPV64" } } )

**Comment by gergnz** [comment]
Hi @bksaurabh96 ,

The following worked for me:

```js
  "Mappings": {
    "AWSInstanceType2Arch": {
      "t1.micro": {
        "Arch": "PV64"
      },
      "t2.nano": {
        "Arch": "HVM64"
      }
    },
    "AWSInstanceType2NATArch": {
      "t1.micro1": {
        "Arch": "NATPV64"
      }
    }
  }
```
```ruby
Mapping(:AWSInstanceType2Arch,
  't1.micro': { Arch: "PV64" },
  "t2.nano": { "Arch": "HVM64" }
)
Mapping(:AWSInstanceType2NATArch,
  "t1.micro1": { "Arch": "NATPV64" }
)
```
