### ISSUE TITLE
"Reverse convert" (Convert existing JSON template into cfndsl Ruby)?

### ISSUE THREAD

**Issue by suan** [stevenjack/cfndsl#234]
_(Preface: I tried searching for any existing issues on this topic but couldn't find any)_

I'm evaluating using either cfndsl or https://github.com/bazaarvoice/cloudformation-ruby-dsl and while I like cfndsl's syntax better, the fact that cloudformation-ruby-dsl has two-way conversion is very attractive. Are there any plans to support reverse conversion (however primitive) here?

**Comment by gergnz** [comment]
Hi @suan,

That's a good question. I haven't seen anyone ask for it.  I know a few colleagues and friends have used (and wrote) [cfn2dsl](https://github.com/realestate-com-au/cfn2dsl).  This might meet your needs.

I personally have found that it was a great opportunity to revisit our templates and make them smarter (using external parameters for example) and actually reduce the number of templates we had.

Let us know how you get on. Happy to help any way we can and always happy to accept pull requests.

**Comment by suan** [comment]
Looks like `cfn2dsl` while could be improved, definitely works as a reverse converter, thanks for pointing that out!
