### ISSUE TITLE
Support yaml as an output type option

### ISSUE THREAD

**Issue by gergnz** [stevenjack/cfndsl#240]
As per https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/,  we should support YAML as an output type option.

**Comment by cmaxwellau** [comment]
Great start, does this output the more optimised function format? i.e.
`!FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]`

**Comment by gergnz** [comment]
No, I totally cheated model.to_json.to_yaml (basically)

To do the optimised output would need some refactoring, I wanted to get an MVP out soonish though.

**Comment by cmaxwellau** [comment]
Np. I had a thought on refactoring.. mostly beginning with changing the name of jsonable 😀. There are a few other optimisations such as FnGetAtt too

**Comment by eric-tucker** [comment]
Has an updated gem been pushed? I don't think this flag is present in the gem I pulled down just tonight.
