### ISSUE TITLE
Support Import and Export of values for cross stack referencing

### ISSUE THREAD

**Issue by gergnz** [stevenjack/cfndsl#242]
As per https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/, we should add support for exporting and importing references to items.

**Comment by cmaxwellau** [comment]
Is anyone working on this right now? If not I'm happy to run with it, just want to check before coding

**Comment by gergnz** [comment]
@cmaxwellau I haven't started on it, go for it, otherwise I'll probably work on it over the next week.

**Comment by cmaxwellau** [comment]
Thanks @gergnz. I've got a customer that wants it tomorrow. It doesn't seem too difficult so I'll have a crack at it tonight.

**Comment by gergnz** [comment]
That'll be awesome if you bang it out before @kornypoet comes on he can likely review, else I'll check it out first think in the morning.

**Comment by kornypoet** [comment]
@gergnz @cmaxwellau I can have this out tomorrow if you guys haven't started.

**Comment by gergnz** [comment]
@kornypoet, @cmaxwellau I haven't started, I'll let you guys talk it out as I won't have time in the next few days.

**Comment by cmaxwellau** [comment]
@kornypoet @gergnz Initial commit :)
