### ISSUE TITLE
Support for Export/Import values from stacks

### ISSUE THREAD

**Issue by mrvisser** [stevenjack/cfndsl#260]
CloudFormation recently added the ability to [Export](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) an `Output`, and the ability to [Import](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) them in other stacks.

This would be great to have handy as a feature in cfndsl, but at the moment doesn't look like we can add the `Export` directive to an output item.

Also not sure if it's possible to use the `Fn::ImportValue` and `Fn::Sub` functions yet in cfndsl either.

**Comment by herebebogans** [comment]
Both functions were added recently. FnSub is very useful and deprecates the FnFormat cfndsl method.

**Comment by mrvisser** [comment]
Oh great, I didn't make that connection before I opened this issue after browsing recent commits. Looks like all that's needed is Output.Export.

**Comment by mrvisser** [comment]
@kornypoet I don't think this is complete yet. Is it possible to do specify an Output as an Export?

**Comment by kornypoet** [comment]
Take a look at these samples here: https://github.com/stevenjack/cfndsl/blob/master/sample/export.rb
https://github.com/stevenjack/cfndsl/blob/master/sample/import.rb
