### ISSUE TITLE
Metadata in CFN Launch Config

### ISSUE THREAD

**Issue by elmobp** [stevenjack/cfndsl#268]
Seems its unsupported by cfndsl? I had a look at at the types and its not listed on either of them, I am leaving this here for now though I am trying to work on a PR to resolve this but incase you had something on the go now?

**Comment by herebebogans** [comment]
It's support .. sample Launch Config block.

```
  AutoScaling_LaunchConfiguration('LaunchConfig') do
  .....
    Metadata(
      'AWS::CloudFormation::Init': {
        ......
        }
    )
end
```

**Comment by elmobp** [comment]
Hence closing it ;) was a long day :(
