### ISSUE TITLE
ApplicationAutoScaling::ScalableTarget not supported.

### ISSUE THREAD

**Issue by dsmithwfm** [stevenjack/cfndsl#270]
Hello,

I'm working with the default AWS ECS template with ALB autoscaling and it seems the method below is missing.  I checked https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/aws/types.yaml and I didn't see it supported.

undefined method `ApplicationAutoScaling_ScalableTarget' for #<CfnDsl::CloudFormationTemplate:0x007fa63bafab20> (NoMethodError)

**Comment by dsmithwfm** [comment]
I was able to get past this by using a template resource however, support for the type would be good to add.  Also AWS::ApplicationAutoScaling::ScalingPolicy is missing.

**Comment by kornypoet** [comment]
gem version `0.11.9` released
