### ISSUE TITLE
Support for Serverless Application Model

### ISSUE THREAD

**Issue by elmobp** [stevenjack/cfndsl#273]
Hey all,

To support the new Serverless Application Model, we need to define a transform in the root of the template currently not supported by cfndsl, normal templates will continue to function with this but ideally would be nice to see a option like -t that would include the Transform.

**Comment by kornypoet** [comment]
Can you elaborate on what this transform would need to look like?

**Comment by kornypoet** [comment]
I found it: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
It looks like it could be implemented as a Template attribute.

**Comment by elmobp** [comment]
Ya, I done a quick dirty hack of it but ideally we should be able to specify the Transform and Template Versions via CLI

**Comment by kornypoet** [comment]
Implemented with stevenjack/cfndsl#290
