### ISSUE TITLE
issue with json module.

### ISSUE THREAD

**Issue by dsmithwfm** [stevenjack/cfndsl#274]
I'm writing a template for ECS and I have an isssue embedded JSON into the template.  Below is actually taken from an example from the repo https://github.com/neillturner/cfndsl_examples.  It generates a json template but, Cloudformation does not like it:

**"Value of property AssumeRolePolicyDocument must be an object"**

``` 
 Resource("ECSServiceRole") do
      Type("AWS::IAM::Role")
      Property("AssumeRolePolicyDocument", {
    "Statement" => [
      {
        "Action"    => [
          "sts:AssumeRole"
        ],
        "Effect"    => "Allow",
        "Principal" => {
          "Service" => [
            "ec2.amazonaws.com"
          ]
        }
      }
    ]
  })
      Property("Path", "/")
    end

```

Here is the .json output

```

    "ECSServiceRole":
      {
        "Type":"AWS::IAM::Role",
        "Properties":
        {
          "AssumeRolePolicyDocument":
          {
            "Statement":[
              {
                "Action":["sts:AssumeRole"],
                "Effect":"Allow",
                "Principal":
                {
                  "Service":["ec2.amazonaws.com"]
                }
              }
            ]
          },
        "Path":"/"}
      },
```

I've tried everything I can think of and can't seem to get it to output proper json.

**Comment by gergnz** [comment]
Hi @dsmithwfm,

I've take your ruby verbatim and built json from it without issue. I was able to validate and build a stack with no issues.

Are you able to show me the error you are getting?

Thanks,
Greg.

**Comment by dsmithwfm** [comment]
Yes when I build mine I get:

"Value of property AssumeRolePolicyDocument must be an object"

I'm guessing this must be a version issue with a Gem, my Chef install of Ruby or something else.

**Comment by dsmithwfm** [comment]
I'll attach the ruby file is someone has time to take a closer look.  I compared my json output generating this and the original and I see no issue.  I'm think the error in cloudformation could be inaccurate.  We use rake task to generate our template.  This one requires a yaml file with vars like this example:

swagger_ui:
    ami_image_id: ami-41a20f2a
    swagger_ui_version: v1
    wfm_environment: integration
    app_server_instance_type: t2.small
    key_pair: sage2

[swagger_ui_cleaned.txt](https://github.com/stevenjack/cfndsl/files/607595/swagger_ui_cleaned.txt)

**Comment by gergnz** [comment]
Hi @dsmithwfm,

I installed 2.1.8 (which shows up as p440 with --version).  And latest cfndsl (0.11.9) and haven't had an issue. Are you using the latest cfndsl?

```bash
$ ruby -v
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-darwin15.0]
$ bundle
Using cfndsl 0.11.9
Using bundler 1.13.6
$ cfndsl -b x.rb -p > x.json
```

```ruby
CloudFormation do
 Resource("ECSServiceRole") do
      Type("AWS::IAM::Role")
      Property("AssumeRolePolicyDocument", {
    "Statement" => [
      {
        "Action"    => [
          "sts:AssumeRole"
        ],
        "Effect"    => "Allow",
        "Principal" => {
          "Service" => [
            "ec2.amazonaws.com"
          ]
        }
      }
    ]
  })
      Property("Path", "/")
    end
end
```

```js
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "ECSServiceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "ec2.amazonaws.com"
                ]
              }
            }
          ]
        },
        "Path": "/"
      }
    }
  }
}
```

Apologies, not being much help really. Your source ruby looks good, and seems to work fine.

**Comment by dsmithwfm** [comment]
Yes:

$ cfndsl --version
cfndsl 0.11.9

**Comment by gergnz** [comment]
Are you seeing the failure when validating or when building the stack?
e.g. does this pass?
```bash
aws cloudformation validate-template --template-body file://yyy.json
```
I have your code working and am producing a valid template and the validation by cloudformation passes. (If I get a chance later today I'll try and stand the stack up somewhere)

**Comment by dsmithwfm** [comment]
Thanks so much for the effort!  I see it when building the stack.  I tried validating and appreciate this approach.  It will surely make debugging much faster.  I see output in validating.  Now with a faster way to generate an error maybe I can keep poking and find the issue.

$ aws cloudformation validate-template --template-body file://swagger_ui.json
{
    "CapabilitiesReason": "The following resource(s) require capabilities: [AWS::IAM::Role]",

**Comment by kornypoet** [comment]
So a couple things I noticed. If you are using the swagger_ui_cleaned.txt file you attached above, you _will_ get an error about malformed PolicyDocuments. The error is not with the ECSServiceRole, however, it's with the EC2Role, farther down in your template. I copied that resource, created a json template and got the same error as you were seeing.

```ruby
Role 'EC2Role' do
  # The issue here is that this should be a Hash, instead of an array
  AssumeRolePolicyDocument [ 
    Statement: [
      {
        Effect: 'Allow',
        Principal: {
          Service: [
            'ec2.amazonaws.com'
          ]
        },
        Action: [
          'sts:AssumeRole'
        ]
      }
    ]
  ]
end
```

Secondly, when submitting your template, you need to specify the capability option to be able to create IAM roles: `--capabilities CAPABILITY_IAM`.

**Comment by dsmithwfm** [comment]
Closing, I had ec2 where I should in fact have had ecs in this particular role.
