### ISSUE TITLE
eval_file_with_extras with ":raw" seems like it's trying to do two incompatible things

### ISSUE THREAD

**Issue by kdgregory** [stevenjack/cfndsl#279]
I'll start by showing what I'm trying to do (which doesn't work):

```
config.fetch("tiers", []).each do |tier|
  if tier
    all_tasks.push("tier_#{tier}")
    CfnDsl::RakeTask.new("tier_#{tier}") do |t|
      t.cfndsl_opts = {
        verbose: true,
        pretty: true,
        files: [{
          filename: "templates/app.rb",
          output:   "output/sandbox/app-#{tier}.template"
        }],
        extras: [
          [ :yaml, config_file ],
          [ :raw,  "tier=#{tier}" ]
        ]
      }
    end
  end
end
```

So, I'm starting with one template file, and producing output for a set of tiers. There is code in the template file that relies on tier being a Ruby value rather than a CloudFormation parameter. 

As written, the Rake task fails with `undefined local variable or method `dev'` (where "dev" is one of my configured tiers), because the entire raw string is evaluated [here](https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl.rb#L83).

However, if I change the code to include quotes (`"tier=\"#{tier}\""`), then the parameter is stored with the quotes [here](https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl.rb#L80).

Trying to work-around by doing an assignment in the evaulated code fails, because that provides too many arguments to `set_param`.

I may be completely missing the point of `:raw`, but it seems that it shouldn't include the `set_param` call. And if that's true, then there needs to be another way to specify a single-value mapping.

**Comment by kornypoet** [comment]
We are actively working on making the API for converting templates in code better, sorry for this inconvenience. In the meantime, I'd encourage you to look at using either [external parameters](https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/external_parameters.rb)(which you can access programatically), or use the `-D` flag when setting simple key-value pairs on the command line.

The `:raw` directive (and command line flag) are not very safe, nor very intuitive and they will most likely be completely removed in newer versions of `cfndsl`. For the time being, you should be able to achieve what you would like with something like this:

```ruby
config.fetch("tiers", []).each do |tier|
  if tier
    all_tasks.push("tier_#{tier}")
    # Use this way of defining tasks for now
    task "tier_#{tier}" do
      CfnDsl::ExternalParameters.defaults(tier: tier)
      model = CfnDsl.eval_file_with_extras("templates/app.rb", extras: [[ :yaml, config_file ], $stderr)
      output =  "output/sandbox/app-#{tier}.template"
      File.open(output, 'w'){ |f| f.puts model.to_json }
    end
  end
end
```

Hopefully this helps.

**Comment by kdgregory** [comment]
The defaults should work for me; should have thought about that. Thanks.

**Comment by kdgregory** [comment]
For future reference, here's my rewrite of the Rakefile per above:

```
tiers = ["sandbox", "prod"]

tiers.each do |tier|
  task tier do
    ["vpc", "app", "bastion", "db"].each do |s|
      CfnDsl::ExternalParameters.defaults(tier: tier)
      model = CfnDsl.eval_file_with_extras("templates/#{s}.rb", [[ :yaml, config_file ]], $stderr)
      output =  "output/sandbox/#{s}-#{tier}.template"
      File.open(output, 'w') do |f|
        f.puts JSON.pretty_generate(model)
      end
    end
  end
end
```

**Comment by kornypoet** [comment]
Thanks @kdgregory
