### ISSUE TITLE
Variable Number of Instances to a LoadBalancer

### ISSUE THREAD

**Issue by nikhithn** [stevenjack/cfndsl#285]
I have been using CFNDSL to allow me to deploy a variable number of EC2 instances using loops and external_parameters, etc.  Essentially the user will input the number of instances to create, and there is a loop that will run and create all of them in the cloudformation template.  

I would like to add all of the instances to a Loadbalancer, so the ElasticLoadBalancing_LoadBalancer resource with a property instances that looks like this in the template:
        "Instances": [
          { "Ref": "instance1" },
          { "Ref": "instance2" },
          ... 
          { "Ref": "instanceN" },      
        ],
How can I achieve this using cfndsl?  I've tried storing instances as an array (instArray), and then dropping it (instArray.drop(0)) but I need to include the Ref.

**Comment by ampedandwired** [comment]
You could try something like this:
```ruby
CloudFormation {
  num_instances = external_parameters.fetch(:num_instances, 3)

  instance_names = (1..num_instances).map do |i|
    instance_name = "instance#{i}"
    EC2_Instance(instance_name) {
      InstanceType "t2.micro"
    }
    instance_name
  end

  ElasticLoadBalancing_LoadBalancer("MyELB") {
    Instances(instance_names.map {|name| Ref(name)})
  }
}
```

**Comment by nikhithn** [comment]
Thank you!  I had been using instance_names.each instead of map, but map makes much more sense since the Ref function needs to be applied to the element before it is added to the instances property.
