### ISSUE TITLE
Hyphen in external parameter key throws obscure error 

### ISSUE THREAD

**Issue by aelsabbahy** [stevenjack/cfndsl#286]
The error message that's thrown when the external params file has a key defined with a hyphen in it is unclear. A clearer error would make this much quicker to troubleshoot.

Steps to reproduce:
test.rb:
```rb
CloudFormation {}
```
params.yml:
```yaml
---
dashes-dont_work: nope
```

```
cfndsl -y params.yml test.rb
cfndsl.rb:63:in `eval_file_with_extras': undefined local variable or method `dashes' for CfnDsl:Module 
```

The error appears to be caused by this line, when `key` variable has a dash in it and ruby tries to `eval` the string:
https://github.com/stevenjack/cfndsl/blob/42dc9f0d13c0d1637835e62d5c5db3f2d1ab2628/lib/cfndsl/external_parameters.rb#L46

**Comment by kornypoet** [comment]
Sorry about the unclear error message. Make sure you have the latest version of `cfndsl` and then use the `-b` flag when converting templates using the executable; this should give you the key-value behavior you are looking for.

The eval code you highlighted is a holdover from a previous way of handling external parameters, by setting them as local variables. That will most likely be removed completely in newer versions of the code (one of the limitations being this very issue).

**Comment by aelsabbahy** [comment]
Thanks for clarifying, feel free to close this issue if there's another one tracking the deprecation.
