### ISSUE TITLE
Error specifying an SSL certificate when using an ALB

### ISSUE THREAD

**Issue by dsmithwfm** [stevenjack/cfndsl#287]
This maybe a formatting issue but I can't seem to specify a certificate for my ALB using an ECS template.

I've tried formatting this every way I can think of and looked at working examples people have used with other DSL's.

Here is the error from Cloudformation

	Value of property Certificates must be a list of objects

Here is my resource definition:

```  
  ElasticLoadBalancingV2_Listener 'ALBListener' do
    DefaultActions [
      {
        TargetGroupArn: Ref('ECSTargetGroup'),
        Type: 'forward'
      }
    ]
    Certificate [
      {
        CertificateArn: 'arn:aws:acm:us-east-1:12345678910:certificate/92380811-95a2-4da6-9fc9-8ee1c6f3226e'
      }
    ]
    LoadBalancerArn Ref('SwaggerUiAlb')
    Port '443'
    Protocol 'HTTPS'
  end
```

**Comment by kornypoet** [comment]
Can you post your resulting Json?

When dealing with a plural property like [Certificates](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html#cfn-elasticloadbalancingv2-listener-certificates) you can either singularize the method in `cfndsl` and provide a single argument, which the dsl will Array-ify for you, or you specify the plural form of the method, and provide it with an array of arguments:
```ruby
Certificate(CertificateArn: 'arn:aws:acm:us-east-1:xxx:certificate/xxx')

# or

Certificates [
  {
    CertificateArn: 'arn:aws:acm:us-east-1:xxx:certificate/xxx'
  }
]
```

The properties allowed for an ALB are defined [here](https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/aws/types.yaml#L605-L612), which has been ported from the CloudFormation documentation. Both of the above should result in the same JSON output:

```json
"Certificates": [          
    {
      "CertificateArn": "arn:aws:acm:us-east-1:xxx:certificate/xxx"          
    }        
],
```

Now, if your JSON output still looks correct, it may be an issue with the documentation of the API itself.

**Comment by dsmithwfm** [comment]
Thanks for the fast reply.  The first suggestion worked perfectly.  I guess I failed reading the AWS documentation and was using Certificate from my experience with ELB's.  It all makes sense now.
