### ISSUE TITLE
Error setting variable with '.'

### ISSUE THREAD

**Issue by mezzatto** [stevenjack/cfndsl#288]
If I use something like this:
```
--define "instance_type=c4.8xlarge"
```

I get this error:

```
Running raw ruby code instance_type=c4.8xlarge
/vivareal/cfndsl/lib/cfndsl.rb:83:in `eval': raw code:1: syntax error, unexpected $undefined (SyntaxError)
instance_type=c4.8xlarge
                 ^
raw code:1: no .<digit> floating literal anymore; put 0 before dot
instance_type=c4.8xlarge
                  ^
	from /vivareal/cfndsl/lib/cfndsl.rb:83:in `block in eval_file_with_extras'
	from /vivareal/cfndsl/lib/cfndsl.rb:65:in `each'
	from /vivareal/cfndsl/lib/cfndsl.rb:65:in `eval_file_with_extras'
	from /vivareal/cfndsl/bin/cfndsl:75:in `<top (required)>'
	from /usr/local/bundle/bin/cfndsl:16:in `load'
	from /usr/local/bundle/bin/cfndsl:16:in `<main>'
```

This error do not allow me to specify a dynamic instance type for my EC2 instance :(

**Comment by kornypoet** [comment]
Make sure you either:
Use the `-b` flag to disable variable-binding (the recommended way). This will set `instance_type` as a key in the external parameters hash with `c4.8xlarge` as its value.

Or, make sure you properly quote the variable `-D 'instance_type="c4.8xlarge"'`. This will set `instance_type` as a local variable in your template. (This behavior is deprecated and will be removed in a future release).

**Comment by mezzatto** [comment]
Using `-D 'instance_type="c4.8xlarge"'` generated this:

```
"InstanceType":"\"c4.8xlarge\""
```

Which is a valid JSON, but not a valid CloudFormation one.

**Comment by kornypoet** [comment]
Which invocation did you use?

For the following template:

```ruby
# sample/my_template.rb
CloudFormation do
  Description 'My Description'

  EC2_Instance(:myInstance) do
    ImageId 'ami-12345678'
    InstanceType instance_type
  end
end
```

Using `bin/cfndsl sample/my_template.rb -D 'instance_type="c4.8xlarge"' -p` should generate this:

```
The creation of constants as config is deprecated!
Please switch to the #external_parameters method within your templates to access variables
See https://github.com/stevenjack/cfndsl/issues/170
Use the --disable-binding flag to suppress this message
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "My Description",
  "Resources": {
    "myInstance": {
      "Properties": {
        "ImageId": "ami-12345678",
        "InstanceType": "c4.8xlarge"
      },
      "Type": "AWS::EC2::Instance"
    }
  }
}
```

If you are using external parameters in your template like so:

```ruby
# sample/my_template.rb
CloudFormation do
  Description 'My Description'

  EC2_Instance(:myInstance) do
    ImageId 'ami-12345678'
    InstanceType external_parameters[:instance_type]
  end
end
```

Then you need the following invocation, disabling binding and no longer needing special quoting:

`bin/cfndsl sample/my_template.rb -D instance_type=c4.8xlarge -p -b` which should generate:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "My Description",
  "Resources": {
    "myInstance": {
      "Properties": {
        "ImageId": "ami-12345678",
        "InstanceType": "c4.8xlarge"
      },
      "Type": "AWS::EC2::Instance"
    }
  }
}
```

The latter is the preferred way.

**Comment by kornypoet** [comment]
The combination of `-D` and `-y` should work just fine, and in fact, you can have multiple `-y` options (which is what I would recommend in this case). They will apply in left to right order (from the command line) with any `-D` options applying last. With external_parameters, the `-D` flag is assumed to be key-value pairs, which is why it's breaking when you pass it a hash. Either flatten the hash to a single level, or put it into an additional yaml file.
If you truly need the `-D` flag to accept raw ruby, then you should _not_ use the `-b` flag, and you should not try to access those values through external_parameters. However, this is the old binding behavior.

**Comment by mezzatto** [comment]
👍
