### ISSUE TITLE
rake aborted! Seahorse::Client::NetworkingError:execution expired  

### ISSUE THREAD

**Issue by jaydo1** [stevenjack/cfndsl#294]
I've been using rake to do mass deployments which have been working fine but on the last deployment, we received this error,
rake aborted! Seahorse::Client::NetworkingError:execution expired  
C:/Cloudformation/Rake:86:in `block(2 levels)in<top(required)>'
C:/Cloudformation/Rakefile:81in `each'
C:/Cloudformation/Rakefile:81in `block in <top>(required)>`
Task:TOP =>deploy (See full trace by running task with --trace)

Any help would be greatly appreciated

**Comment by gergnz** [comment]
Hi @jaydo1,

This doesn't look like a cfndsl error, but rather a connection issue to AWS with the ruby SDK. I'm reasonably sure we aren't making any network connections in the released code base.

A quick google showed up this: https://github.com/aws/aws-sdk-ruby/issues/904. Maybe this will help?

If you still believe this is a cfndsl error. Please try and capture a trace so we can see where in cfndsl it is breaking.

Thanks and good luck!
