### ISSUE TITLE
Support for Lambda backed custom resources with shorthand

### ISSUE THREAD

**Issue by elmobp** [stevenjack/cfndsl#315]
Currently cfndsl does not support short hand for custom resources so it gets very ugly. An idea (Which I plan to raise a PR when I get time) would be not to validate anything thats inside of a CloudFormation_CustomResource.

If you have a look ServiceToken works fine?

**Comment by kornypoet** [comment]
It's a little harder than simple not validating: the methods need to be defined on the custom resource object. Allowing people to type in _whatever_ and simply accepting could lead to a lot of weird errors, and strange behavior. 
If you talking about shorthanding the ServiceToken property itself, I guess I would like to see suggestions for helper methods that are both general enough for most use-cases and actually shorten the syntax significantly.
I've used CustomResources a bit, and while I agree they can be pretty ugly, we are running close the edge of what we can really improve there.

**Comment by elmobp** [comment]
Hm ServiceToken is fine short hand as it currently is, Im not sure how to really approach this either maybe even support a property hash or something in there?

```ruby
Properties {
'foo' => 'bar',
'a' => 'b'
}
```

Still looks nicer than Property heh

**Comment by kornypoet** [comment]
That is doable, and I actually had to double-check that it wasn't already possible. It fits the singularizing method definitions we already use, so nothing surprising. I can't imagine it's too much work to make `Properties` work for every resource.

**Comment by elmobp** [comment]
Im not to fussed just seems nicer than Property('xxx', 'xxx')
