### ISSUE TITLE
Error reading specification file on 0.13.0

### ISSUE THREAD

**Issue by arothian** [stevenjack/cfndsl#322]
Hey folks,

Pulled down the new gem version today, and it is failing with:
```
cfndsl-0.13.0/lib/cfndsl/specification.rb:83:in `read': No such file or directory @ rb_sysopen - <HOMEPATH>/.cfndsl/resource_specification.json (Errno::ENOENT)
```

The magic that happens here: https://github.com/stevenjack/cfndsl/blob/master/bin/cfndsl#L75 only works if directly using the executable CLI. I'm using `CfnDsl.eval_file_with_extras` directly within ruby, leading to this file not existing. 

Thoughts? It seems odd to have this magic configuration in the bin file. Perhaps move the check into https://github.com/stevenjack/cfndsl/blob/d31ba4b82f4f0ecaa83af6060e42b157be3678d4/lib/cfndsl.rb#L58?

**Comment by kornypoet** [comment]
Good catch, let me take a look.

**Comment by gergnz** [comment]
@arothian are you happy this issue is now resolved?

**Comment by arothian** [comment]
Yeah, the fix looks good. Thanks for checking back.
