### ISSUE TITLE
Please add support for multiple input files with deep merge

### ISSUE THREAD

**Issue by eric-tucker** [stevenjack/cfndsl#327]
It would be nice if we could specify multiple input files so that we can have a common set of input for any cfndsl call and then different input files for various components.

I envision something like this:
```
cfndsl ----yaml common.yml --yaml app_specific.yaml my_cfndsl_template.rb
```

The contents should be merged, with subsequent files overwriting any duplicate keys (with a deep yaml merge) in order of input files specified on the CLI.

**Comment by gergnz** [comment]
Hi @eric-tucker,

Besides the merge, you can do this today, it just overrides keys instead of merging.

I wonder if we'd want to add an option for backwards compatibility or an option to do merging.

Sounds like a good idea, would welcome a pull request :)

**Comment by gergnz** [comment]
@eric-tucker want to give this ago? https://github.com/gergnz/cfndsl/tree/deepmerge327

**Comment by eric-tucker** [comment]
Awesome.  I'll definitely give this a shot.

**Comment by eric-tucker** [comment]
@gergnz this is going to sound dumb, but is there a documented build process for this (to make a gem) or should I just clone and run directly from the repo at `bin/cfndsl`?

**Comment by gergnz** [comment]
@eric-tucker good question.

You could achieve it two ways:

1. Use git in the Gemfile:
```ruby
gem 'cfndsl', '0.13.1', :git => 'git@github.com:gergnz/cfndsl.git', :branch => 'deepmerge327'
```
2. create a _test_ folder inside a clone of cfndsl and dump test code in there:
```bash
test/
├── 1.yml
├── 2.yml
└── test.rb
$ cfndsl -p -b -y test/1.yml -y test/2.yml test/test.rb
```

Hope that helps.

**Comment by gergnz** [comment]
Of course you could just build a gem too:
```bash
gem build cfndsl.gemspec
```

**Comment by eric-tucker** [comment]
So I did this:

```
gem build cfndsl.gemspec
sudo gem install cfndsl-0.13.1.gem 
```

When I try to run cfndsl (I uninstalled all previous versions):

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- deep_merge (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/cfndsl-0.13.1/lib/cfndsl.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/cfndsl-0.13.1/bin/cfndsl:110:in `<top (required)>'
        from /usr/local/bin/cfndsl:23:in `load'
        from /usr/local/bin/cfndsl:23:in `<main>'
```

Should this not have been brought in by the gem build?

**Comment by eric-tucker** [comment]
Apparently my experience with bundler is non-existent.  Got past the above figuring out the purpose of the Gemfile.

**Comment by gergnz** [comment]
Sorry about that. Fixed.

**Comment by eric-tucker** [comment]
@gergnz this is working great.  I would LOVE to see this brought into mainline.  I appreciate having deep merge be the default.

What can be done to get this merged?

**Comment by kornypoet** [comment]
Just a thought: so far we've been able to keep out external dependencies. ActiveSupport has a `#deep_merge` implementation that we could lift (something like 20 lines). @gergnz how do you feel about that approach?

**Comment by gergnz** [comment]
@kornypoet it seems ActiveSupport deep_merge only merges hashes, where as @danielsdeleo version seems to be a lot smarter and can merge arrays and hashes or I'm doing something wrong.

**Comment by gergnz** [comment]
@kornypoet I've merged in deep_merge from @danielsdeleo as the ActiveSupport one doesn't merge as I would expect it to and raised #328. Thoughts?
