### ISSUE TITLE
list cfndsl equivalents

### ISSUE THREAD

**Issue by kidbrax** [stevenjack/cfndsl#336]
when you run `cfndsl -l` it would be great if it listed the cfndsl(ruby) equivalents of each resource. maybe something like this:

```
$cfndsl -l
...
AWS::EC2::Instance -> EC2_Instance
...
```

**Comment by gergnz** [comment]
Interesting idea @kidbrax.

Do you mean something like this:
```bash
$ cfndsl -l | awk -F:: '{print $1"::"$2"::"$3" -> "$2"_"$3}'
AWS::ApiGateway::Account -> ApiGateway_Account
AWS::ApiGateway::ApiKey -> ApiGateway_ApiKey
AWS::ApiGateway::Authorizer -> ApiGateway_Authorizer
AWS::ApiGateway::BasePathMapping -> ApiGateway_BasePathMapping
AWS::ApiGateway::ClientCertificate -> ApiGateway_ClientCertificate
AWS::ApiGateway::Deployment -> ApiGateway_Deployment
AWS::ApiGateway::DomainName -> ApiGateway_DomainName
AWS::ApiGateway::Method -> ApiGateway_Method
AWS::ApiGateway::Model -> ApiGateway_Model
AWS::ApiGateway::Resource -> ApiGateway_Resource
AWS::ApiGateway::RestApi -> ApiGateway_RestApi
AWS::ApiGateway::Stage -> ApiGateway_Stage
```

**Comment by kidbrax** [comment]
Yes, that works great. But I thought some of them were non-standard for some reason and so that conversion isn't accurate 100% of the time.  I swore I had issues with that in the past, but could be wrong.

**Comment by gergnz** [comment]
If you've had issues in the past with any names not matching as expected, would love to hear about it.  The code pretty much builds up a giant list based on the types.yaml or the json spec (depending if you are on the old code or new).

The AWS is then implied. You can actually use __AWS_EC2_Instance__ if you want.
