### ISSUE TITLE
How to embed parameter into string?

### ISSUE THREAD

**Issue by kidbrax** [stevenjack/cfndsl#341]
I'd like to construct a ECR url such as this:

`123456.dkr.ecr.us-east-1.amazonaws.com/foo:20170923`

But I'd like for the timestamp at the end to come from a parameter:

```
Parameter 'ImageTag' do
  Description           'The timestamp tag of the image that should be used when running the service'
  Type                  'String'
end
```

So is there a way to use Ref('ImageTag') to build a string? similar to this?

`"123456.dkr.ecr.us-east-1.amazonaws.com/foo:#{Ref('ImageTag')}"
`

**Comment by ans0600** [comment]
@kidbrax Not sure if I fully get your question but I guess you probably looking for this:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html

Basically, you can join the 2 refs using FnJoin("",[Ref("ECR"),Ref("ImageTag")])

**Comment by kidbrax** [comment]
Yes, i realized that right after i created this issue.  Thanks for following up though.

**Comment by mikechau** [comment]
@kidbrax or for anyone else interested you can also use `FnSub`:

```ruby
FnSub("123456.dkr.ecr.us-east-1.amazonaws.com/foo:${ImageTag}")
```

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
