### ISSUE TITLE
"AWS::SNS::Topic" does not appear to be fully defined

### ISSUE THREAD

**Issue by perkof** [stevenjack/cfndsl#81]
Hi there,

Thanks for all your great work on this gem. I have been using it very heavily.

It looks like AWS::SNS::Topic is not fully defined in the YAML file. I am happy to create a PR that fixes this one up.

If you could provide some guidance on your preferred path to contribution that would also be really helpful. Would you prefer I create issue and put then create the PR off the back of that for changes such as this? Or is a simple PR on its own sufficient?

Fraser

**Comment by howech** [comment]
A simple PR should suffice.

**Comment by perkof** [comment]
PR @ https://github.com/stevenjack/cfndsl/pull/80 

Interested to hear your thoughts.
