### ISSUE TITLE
Help with conditions

### ISSUE THREAD

**Issue by elnica6** [stevenjack/cfndsl#82]
Hello-

I'm trying to setup a condition in my cfndsl but keep getting the following error (I suspect something is wrong with my syntax). 
```
Undefined symbol: fnEquals(#<CfnDsl::RefDefinition:0x007f90799f4d98 @Ref="Environment">, "infrastructure01")
```

Here is my code:
```
#my parameter I'm basing my condition off of
  Parameter("Environment") {
    String
    Description "The environment/vpc name"
    AllowedValues [
      "infrastructure01",
      "lab01"
    ]
  }

#
# a bunch of different resources here like Roles, Policies, Instances, Security Groups, etc, etc
#

#my condition referencing the parameter stated above
Condition("PrivateIPCondition", fnEquals(Ref("Environment"),"infrastructure01"))
```

If I comment out the Condition, my template renders perfectly. Can't seem to get the condition piece working right. What am I doing wrong here?

Thanks for the great tool and the help!

**Comment by elnica6** [comment]
any love on this please? I can't seem to find any examples on using the condition resource...thanks!

**Comment by stevenjack** [comment]
@elnica6 try `FnEquals` instead of `fnEquals`.

**Comment by elnica6** [comment]
Sorry for the delayed response, but I'm good to go now. Thank you!
