### ISSUE TITLE
cfndsl_examples

### ISSUE THREAD

**Issue by neillturner** [stevenjack/cfndsl#83]
I have created a set of examples at: 
  https://github.com/neillturner/cfndsl_examples
using cfn2dsl 
from Amazon AWS Template Snippets
 http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/CHAP_TemplateQuickRef.html

**Comment by stevenjack** [comment]
@neillturner These are great, just thinking of the best way of incorporating these.. @howech shall we put them in the examples folder?

**Comment by neillturner** [comment]
Don't you can always point to them in your docs.

**Comment by howech** [comment]
I am not opposed to either approach (adding a link in the dox, or adding
them to the examples).

**Comment by yumpy** [comment]
I'd like to see these sample files being used as part of a cfndsl test suite. The original json template snippets have many un-resolved references and would need to be tidied up so that cfn2dsl can generate files that can be used by cfndsl to 're-generate' the original json.

**Comment by neillturner** [comment]
I have expanded https://github.com/neillturner/cfndsl_examples with more examples and organised into directories. A little disappointed that google 'cfndsl examples' doesn't show my link. if more people link to it, it will go up the rankings.

**Comment by stevenjack** [comment]
@neillturner sorry about the delay on this, I think @yumpy has a good point of these being run as part of the test suite.. I think it makes more sense for them to be part of the repo then so we can enhance the the test suite.

We can add in guidelines for when people add new fields to types that they also need to be added to the corresponding examples, would do you think?
