### ISSUE TITLE
Oddity where do/end block breaks expectations, but {} works fine?

### ISSUE THREAD

**Issue by Integralist** [stevenjack/cfndsl#86]
Hi @howech @stevenjack 

The following code will happily generate correct CloudFormation...

```ruby
alarms = []

alarms.push Resource("CPUAlarmHigh") {
  Type "AWS::CloudWatch::Alarm"
  Property "AlarmDescription", "Scale-up if CPU > 80% for 1 minutes"
  ...other properties...
}

alarms.each do |alarm|
  alarm.declare {
    Property "MetricName", "CPUUtilization"
    ...other properties...
  }
end
```

But if you change `{}` on `alarms.push Resource("CPUAlarmHigh") {}` to be `do/end` like so:

```ruby
alarms.push Resource("CPUAlarmHigh") do
  ...code...
end
```

Then I've found that the `Type "AWS::CloudWatch::Alarm"` doesn't get applied to the generated CloudFormation.

Any ideas why this is?

**Comment by gonzalo-bulnes** [comment]
Hello @Integralist,

It look like a precedence issue, does [this explanation](https://stackoverflow.com/a/6179505) make sense to you?

**Comment by howech** [comment]
I thing Gonzalo is right - its a ruby precedence thing. Calling functions
without using parans to indicate parameters can sometimes get you in
trouble.

**Comment by Integralist** [comment]
Turns out the issue is related to using `push` over `<<`. Using the double chevron fixed the problem. Previously where I had changed from `{}` to `do/end` seemed to not be the actual cause.

**Comment by stevenjack** [comment]
@Integralist you happy for this issue to be closed?

**Comment by Integralist** [comment]
Yup
