### ISSUE TITLE
FnNot() feels awkward

### ISSUE THREAD

**Issue by willglynn** [stevenjack/cfndsl#90]
I find myself writing things like `FnNot(FnEquals(…))`, which is wrong, since this compiles to `{ "Fn::Not": { "Fn::Equals": … } }`. `Fn::Not` takes a single element array, so the correct formulation is `FnNot([FnEquals…])` instead.

I don't believe it's ever correct to call `FnNot()` with any parameter other than a single-element array, so… can we make the natural syntax valid? That is, if `FnNot()` gets something that's not an array, can we automatically wrap it in one?

**Comment by rowanu** [comment]
Just ran in to this issue where `FnNot` requires an array argument, but the other `Fn*` methods do not - is that intentional?
