### ISSUE TITLE
PreferredAvailabilityZone Property on ElastiCache_CacheCluster is incorrect

### ISSUE THREAD

**Issue by Netmaster80** [stevenjack/cfndsl#92]
cfndsl is expecting the property to be spelled "PreferrredAvailabilityZone" but cloudformation is expecting "PreferredAvailabilityZone", current workaround is to compile it and then fix the json file manually. Can you please change this?

**Comment by stevenjack** [comment]
Mind putting a PR in to fix it?

**Comment by Netmaster80** [comment]
Pull request #94.

Thanks
